// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bdupjgeuxgpjnmjajmqq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJkdXBqZ2V1eGdwam5tamFqbXFxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyODA5NDYsImV4cCI6MjA2Njg1Njk0Nn0.Mbe7loM3BaZQfLjEth5BwmDx1F2CjfRPIkbofatuWts";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});